### PR TITLE
ci: stop test build of docs on circleci, update RTD config

### PR DESCRIPTION
**Pull request by consideRatio**
We have been using CircleCI alongside RTD to run tests, and now we got an error on CircleCI because it was using python 3.6 that was no longer compatible with a package we installed.

So, I'm removing that duplicated CI logic in circleci in favor of relying on the test builds now supported by RTD, which is also responsible for building/publishing.

This should resolve the build error observed in #249.

### CODE REVIEW

**Review by sgibson91 — APPROVED** [review]
LGTM!

**Comment by consideRatio** [comment]
Thanks @sgibson91!

**Comment by manics** [comment]
Don't forget to disable the CircleCI build in https://app.circleci.com/projects/project-dashboard/github/jupyterhub/ when removing it from future projects to avoid an error status or PRs :smile:

**Comment by consideRatio** [comment]
@manics ah I didn't know about that part, thanks!

**Pull request merged**
