### PR TITLE
Update about.rst

### PR DESCRIPTION
**Pull request by betatim**
Fix a syntax error

### CODE REVIEW

**Comment by consideRatio** [comment]
:tada: nice!

**Comment by betatim** [comment]
What I don't understand is why https://mybinder--222.org.readthedocs.build/en/222/about/about.html (the RTD deploy preview) still shows the broken state?

**Comment by consideRatio** [comment]
@betatim for me the RTD build link also seem to work with valid links!

**Comment by betatim** [comment]
For me it still looks like this:

Screenshot 2020-11-27 at 09 56 21

Super weird

**Comment by consideRatio** [comment]
Here is what i see

**Pull request merged**
