### PR TITLE
Make Dockerfile docs accurate

### PR DESCRIPTION
**Pull request by yuvipanda**
These used to be accurate, but no longer are! Someone showed up on the binder gitter just now 
with problems caused by this doc being out of date, so I've updated it.

### CODE REVIEW

**Comment by yuvipanda** [comment]
@minrk @choldgraf @willingc I'm self merging this now since at least one user used these docs and produced a non-working Dockerfile. But do review this after, and I'll update as necessary (or you can too!) - I feel the prose is a bit stilted.

**Comment by willingc** [comment]
Thanks @yuvipanda for the changes. I'm going to rewrite these docs tomorrow and resubmit a PR for review by @minrk @choldgraf and you. I plan to make the prose more succinct and action oriented as well as run all through the checkers that I have used.

In general, I think it would be better when running across these errors and out of date info comes up to make the minimal change needed for a quick doc edit (which is ok to self merge if truly critical) and then create an issue or larger PR for the overall review of the content. In most cases, a 24 hour review cycle is preferable and minimizes the possibility of things falling through the cracks. Yes, we want to be responsive to users, but many times 24-48 hours will not matter especially if the issue and/or PR is open since most users will search the repo.

**Comment by yuvipanda** [comment]
Thanks @willingc. 

I think I'm still in the mode of 'early project with one person working on it' in some ways, and that's not useful now. I'll actively adjust!

**Comment by willingc** [comment]
I understand and appreciate it 🍨

**Pull request merged**
