### PR TITLE
Mention possible location of configuration files in documentation

### PR DESCRIPTION
**Pull request by astrojuanlu**
This was mentioned in the repo2docker docs, but not on the binder ones.

In addition, I used this opportunity to enable intersphinx in the repository.

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Sphinx 4.0.3 got installed, which doesn't have the `add_stylesheet` method anymore.

On the other hand:

```
Traceback (most recent call last):
  File "federation/gen_federation.py", line 3, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
```

Unsure how to continue 🤔

**Comment by astrojuanlu** [comment]
Oh I see, a couple of extensions pull `sphinx>=2`. Easy fix.

**Comment by astrojuanlu** [comment]
Rendered version: https://mybinder--236.org.readthedocs.build/en/236/config_files.html#configuration-files

**Comment by choldgraf** [comment]
looks great - thanks very much! :-)

**Pull request merged**
