### PR TITLE
add example repository (tensorboard)

### PR DESCRIPTION
**Pull request by btel**
This PR adds an example to the community section. The interest of the example is that:

* it shows how to use tensorboard on binder or other jupyter-based environments. In such environments, tensorboard can not be often used because it creates a webapp that listens on a port that is not visible to the outside world,

* it uses the jupyter-proxy-server extension that solves the above problem

* it launches the tensorboard in the background, so that it is immediately available after launching the nootebook.

The examples lives in my GH account so far, but I am happy to move it elsewhere (binder-examples) as needed.

See also https://github.com/jupyterhub/jupyter-server-proxy/issues/41 for background information.

### CODE REVIEW

**Comment by choldgraf** [comment]
Hey - this is really cool! If you'd be willing to move this into `binder-examples` that'd be awesome. I'm happy to help review and add a bit of extra documentation etc. What do you think?

If you're +1 on that, I'd suggest something like:

1. Initiate a transfer of that repo to `binder-examples`
2. I'll make sure you have admin rights on the repo
3. We polish the README to clean up the explanations etc.

It's a nice example of using the server proxy, and also more generally using tensorboard :-)

**Comment by btel** [comment]
cool! It sound like a good plan. I will be happy to move it to `binder-examples`. :tada:

**Comment by choldgraf** [comment]
cool! lemme know when you've made the transfer

**Comment by btel** [comment]
I don't seem to have permission to create repositories under binder-examples org. When I try to transfer the ownership of my repo to binder-examples, I get the following message:

"You don’t have the permission to create public repositories on binder-examples."

**Comment by choldgraf** [comment]
@btel I just imported your repository into a new binder-examples one and added you as an admin!

https://github.com/binder-examples/tensorboard/invitations

Wanna make a PR to that repository to improve the README a little bit, modeling it after the other READMEs in that organization?

**Comment by btel** [comment]
Sure, I will do that. Thanks!

**Comment by choldgraf** [comment]
ok, I'll close this one then :-)

**Pull request closed without merging**
