### PR TITLE
Update dockerfile requirements

### PR DESCRIPTION
**Pull request by yuvipanda**
JupyterHub is no longer required

### CODE REVIEW

**Comment by choldgraf** [comment]
this is awesome!

**Comment by choldgraf** [comment]
I'm gonna hold off on merging until @minrk has a chance to take a look

**Comment by yuvipanda** [comment]
I'm making more changes, but the current docs are actively inaccurate so I think we should merge sooner than later :) They used to be accurate before last week.

**Comment by choldgraf** [comment]
sounds good - if these are stop-gap "unbreak the docs" changes then feel free to self-merge as I've got to step away for a couple of hours now

**Comment by yuvipanda** [comment]
Subsumed into #18 because of whitespace related rebase issues.

**Pull request closed without merging**
