### PR TITLE
Added Shiny app example

### PR DESCRIPTION
**Pull request by pablobernabeu**

### CODE REVIEW

**Comment by betatim** [comment]
Nice work!

I just tried to start the example and got stuck with the usual problem of R repos: they take a long time to build. Which made me wonder: does it make sense to link to a particular revision of the example repo instead of `master` so that users don't have to wait for rebuilds? We can then periodically update which revision the example links to to get new changes in.

**Comment by pablobernabeu** [comment]
Thank you!

I didn't know that specific versions took less time to build. Sounds great. I'll edit the link.

**Comment by betatim** [comment]
Thanks! They don't build faster but they (should) require building less often. So the time to launch them should be shorter for more people (as less people need to wait for a build). (What a convoluted sentence :) )

**Comment by choldgraf** [comment]
wooo! thanks @pablobernabeu :-)

**Comment by pablobernabeu** [comment]
My pleasure!

**Pull request merged**
